
platform :ios, '9.0'

target 'YDImageService_Example' do
  pod 'YDImageService', :path => '../'

  target 'YDImageService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
